const mockPostListData = [
    {
        userId: 1,
        postId: 1,
        image: 'flower.jpg',
		id: 13,
		timestamp: 13,
		description: 'an image i captured',
		likes: [],
		comments: [],
    },
    {
        userId: 2,
        postId: 2,
        image: 'sunset.jpg',
		id: 13,
		timestamp: 13,
		description: 'an image i captured',
		likes: [],
		comments: [],
    },
    {
        userId: 3,
        postId: 3,
        image: 'goldengate.jpg',
		id: 13,
		timestamp: 13,
		description: 'an image i captured',
		likes: [],
		comments: [],
    },
    {
        userId: 4,
        postId: 4,
        image: 'bee.jpg',
		id: 13,
		timestamp: 13,
		description: 'an image i captured',
		likes: [],
		comments: [],
    },
    {
        userId: 5,
        postId: 5,
        image: 'verywide.jpg',
		id: 13,
		timestamp: 13,
		description: 'an image i captured',
		likes: [],
		comments: [],
    },
    {
        userId: 6,
        postId: 6,
        image: 'trees.jpg',
		id: 13,
		timestamp: 13,
		description: 'an image i captured',
		likes: [],
		comments: [],
    },

];
export default mockPostListData;